/* 
 * model-information-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using DHICN.PAAS.SDK.ModelInformation.Client;
using DHICN.PAAS.SDK.ModelInformation.Model;

namespace DHICN.PAAS.SDK.ModelInformation.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWDJunctionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 新增节点要素编辑信息 Add junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        Result<Object> ApiV1ModelInformationDomainWdJunctionAddPost (AddJunctionInput addJunctionInput = default(AddJunctionInput));

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Result<Object>> ApiV1ModelInformationDomainWdJunctionAddPostWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput));
        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>List&lt;QueryJunctionDto&gt;</returns>
        Result<List<QueryJunctionDto>> ApiV1ModelInformationDomainWdJunctionAllGet (string scenarioId = default(string));

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>ApiResponse of List&lt;QueryJunctionDto&gt;</returns>
        ApiResponse<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionAllGetWithHttpInfo (string scenarioId = default(string));
        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Object</returns>
        Result<Object> ApiV1ModelInformationDomainWdJunctionDeletePost (DeleteInput deleteInput = default(DeleteInput));

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Result<Object>> ApiV1ModelInformationDomainWdJunctionDeletePostWithHttpInfo (DeleteInput deleteInput = default(DeleteInput));
        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>List&lt;QueryJunctionDto&gt;</returns>
        Result<List<QueryJunctionDto>> ApiV1ModelInformationDomainWdJunctionListGet (string scenarioId = default(string), List<string> muids = default(List<string>));

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>ApiResponse of List&lt;QueryJunctionDto&gt;</returns>
        ApiResponse<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionListGetWithHttpInfo (string scenarioId = default(string), List<string> muids = default(List<string>));
        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        Result<Object> ApiV1ModelInformationDomainWdJunctionResavePost (AddJunctionInput addJunctionInput = default(AddJunctionInput));

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Result<Object>> ApiV1ModelInformationDomainWdJunctionResavePostWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput));
        /// <summary>
        /// 修改节点要素信息 Update junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        Result<Object> ApiV1ModelInformationDomainWdJunctionUpdatePost (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput));

        /// <summary>
        /// 修改节点要素信息 Update junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Result<Object>> ApiV1ModelInformationDomainWdJunctionUpdatePostWithHttpInfo (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWDJunctionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 新增节点要素编辑信息 Add junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionAddPostAsync (AddJunctionInput addJunctionInput = default(AddJunctionInput));

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionAddPostAsyncWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput));
        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>Task of List&lt;QueryJunctionDto&gt;</returns>
        System.Threading.Tasks.Task<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionAllGetAsync (string scenarioId = default(string));

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;QueryJunctionDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<List<QueryJunctionDto>>>> ApiV1ModelInformationDomainWdJunctionAllGetAsyncWithHttpInfo (string scenarioId = default(string));
        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionDeletePostAsync (DeleteInput deleteInput = default(DeleteInput));

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionDeletePostAsyncWithHttpInfo (DeleteInput deleteInput = default(DeleteInput));
        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>Task of List&lt;QueryJunctionDto&gt;</returns>
        System.Threading.Tasks.Task<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionListGetAsync (string scenarioId = default(string), List<string> muids = default(List<string>));

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;QueryJunctionDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<List<QueryJunctionDto>>>> ApiV1ModelInformationDomainWdJunctionListGetAsyncWithHttpInfo (string scenarioId = default(string), List<string> muids = default(List<string>));
        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionResavePostAsync (AddJunctionInput addJunctionInput = default(AddJunctionInput));

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionResavePostAsyncWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput));
        /// <summary>
        /// 修改节点要素信息 Update junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionUpdatePostAsync (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput));

        /// <summary>
        /// 修改节点要素信息 Update junction information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionUpdatePostAsyncWithHttpInfo (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWDJunctionApi : IWDJunctionApiSync, IWDJunctionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WDJunctionApi : IWDJunctionApi
    {
        private DHICN.PAAS.SDK.ModelInformation.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WDJunctionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WDJunctionApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WDJunctionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WDJunctionApi(String basePath)
        {
            this.Configuration = DHICN.PAAS.SDK.ModelInformation.Client.Configuration.MergeConfigurations(
                DHICN.PAAS.SDK.ModelInformation.Client.GlobalConfiguration.Instance,
                new DHICN.PAAS.SDK.ModelInformation.Client.Configuration { BasePath = basePath }
            );
            this.Client = new DHICN.PAAS.SDK.ModelInformation.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new DHICN.PAAS.SDK.ModelInformation.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = DHICN.PAAS.SDK.ModelInformation.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WDJunctionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WDJunctionApi(DHICN.PAAS.SDK.ModelInformation.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = DHICN.PAAS.SDK.ModelInformation.Client.Configuration.MergeConfigurations(
                DHICN.PAAS.SDK.ModelInformation.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new DHICN.PAAS.SDK.ModelInformation.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new DHICN.PAAS.SDK.ModelInformation.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = DHICN.PAAS.SDK.ModelInformation.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WDJunctionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WDJunctionApi(DHICN.PAAS.SDK.ModelInformation.Client.ISynchronousClient client,DHICN.PAAS.SDK.ModelInformation.Client.IAsynchronousClient asyncClient, DHICN.PAAS.SDK.ModelInformation.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = DHICN.PAAS.SDK.ModelInformation.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public DHICN.PAAS.SDK.ModelInformation.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public DHICN.PAAS.SDK.ModelInformation.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public DHICN.PAAS.SDK.ModelInformation.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DHICN.PAAS.SDK.ModelInformation.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        public Result<Object> ApiV1ModelInformationDomainWdJunctionAddPost (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = ApiV1ModelInformationDomainWdJunctionAddPostWithHttpInfo(addJunctionInput);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< Object >> ApiV1ModelInformationDomainWdJunctionAddPostWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = addJunctionInput;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Result< Object >>("/api/v1/model-information/domain-wd/junction/add", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionAddPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionAddPostAsync (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionAddPostAsyncWithHttpInfo(addJunctionInput);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 新增节点要素编辑信息 Add junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionAddPostAsyncWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = addJunctionInput;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Result<Object>>("/api/v1/model-information/domain-wd/junction/add", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionAddPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>List&lt;QueryJunctionDto&gt;</returns>
        public Result<List<QueryJunctionDto>> ApiV1ModelInformationDomainWdJunctionAllGet (string scenarioId = default(string))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>> localVarResponse = ApiV1ModelInformationDomainWdJunctionAllGetWithHttpInfo(scenarioId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>ApiResponse of List&lt;QueryJunctionDto&gt;</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< List<QueryJunctionDto> >> ApiV1ModelInformationDomainWdJunctionAllGetWithHttpInfo (string scenarioId = default(string))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (scenarioId != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("", "scenarioId", scenarioId));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<Result< List<QueryJunctionDto> >>("/api/v1/model-information/domain-wd/junction/all", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionAllGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>Task of List&lt;QueryJunctionDto&gt;</returns>
        public async System.Threading.Tasks.Task<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionAllGetAsync (string scenarioId = default(string))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionAllGetAsyncWithHttpInfo(scenarioId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 获取该方案下所有的节点要素信息 Get all junctions information of a scenario 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;QueryJunctionDto&gt;)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>>> ApiV1ModelInformationDomainWdJunctionAllGetAsyncWithHttpInfo (string scenarioId = default(string))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (scenarioId != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("", "scenarioId", scenarioId));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Result<List<QueryJunctionDto>>>("/api/v1/model-information/domain-wd/junction/all", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionAllGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Object</returns>
        public Result<Object> ApiV1ModelInformationDomainWdJunctionDeletePost (DeleteInput deleteInput = default(DeleteInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = ApiV1ModelInformationDomainWdJunctionDeletePostWithHttpInfo(deleteInput);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< Object >> ApiV1ModelInformationDomainWdJunctionDeletePostWithHttpInfo (DeleteInput deleteInput = default(DeleteInput))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = deleteInput;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Result< Object >>("/api/v1/model-information/domain-wd/junction/delete", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionDeletePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionDeletePostAsync (DeleteInput deleteInput = default(DeleteInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionDeletePostAsyncWithHttpInfo(deleteInput);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 删除节点要素编辑信息 Delete junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionDeletePostAsyncWithHttpInfo (DeleteInput deleteInput = default(DeleteInput))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = deleteInput;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Result<Object>>("/api/v1/model-information/domain-wd/junction/delete", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionDeletePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>List&lt;QueryJunctionDto&gt;</returns>
        public Result<List<QueryJunctionDto>> ApiV1ModelInformationDomainWdJunctionListGet (string scenarioId = default(string), List<string> muids = default(List<string>))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>> localVarResponse = ApiV1ModelInformationDomainWdJunctionListGetWithHttpInfo(scenarioId, muids);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>ApiResponse of List&lt;QueryJunctionDto&gt;</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< List<QueryJunctionDto> >> ApiV1ModelInformationDomainWdJunctionListGetWithHttpInfo (string scenarioId = default(string), List<string> muids = default(List<string>))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (scenarioId != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("", "scenarioId", scenarioId));
            }
            if (muids != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("multi", "muids", muids));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<Result< List<QueryJunctionDto> >>("/api/v1/model-information/domain-wd/junction/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionListGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>Task of List&lt;QueryJunctionDto&gt;</returns>
        public async System.Threading.Tasks.Task<Result<List<QueryJunctionDto>>> ApiV1ModelInformationDomainWdJunctionListGetAsync (string scenarioId = default(string), List<string> muids = default(List<string>))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionListGetAsyncWithHttpInfo(scenarioId, muids);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scenarioId">方案ID scenario id (optional)</param>
        /// <param name="muids">模型中节点ID列表 junction muids (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;QueryJunctionDto&gt;)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<List<QueryJunctionDto>>>> ApiV1ModelInformationDomainWdJunctionListGetAsyncWithHttpInfo (string scenarioId = default(string), List<string> muids = default(List<string>))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (scenarioId != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("", "scenarioId", scenarioId));
            }
            if (muids != null)
            {
                localVarRequestOptions.QueryParameters.Add(DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.ParameterToMultiMap("multi", "muids", muids));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Result<List<QueryJunctionDto>>>("/api/v1/model-information/domain-wd/junction/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionListGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        public Result<Object> ApiV1ModelInformationDomainWdJunctionResavePost (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = ApiV1ModelInformationDomainWdJunctionResavePostWithHttpInfo(addJunctionInput);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< Object >> ApiV1ModelInformationDomainWdJunctionResavePostWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = addJunctionInput;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Result< Object >>("/api/v1/model-information/domain-wd/junction/resave", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionResavePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionResavePostAsync (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionResavePostAsyncWithHttpInfo(addJunctionInput);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionResavePostAsyncWithHttpInfo (AddJunctionInput addJunctionInput = default(AddJunctionInput))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = addJunctionInput;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Result<Object>>("/api/v1/model-information/domain-wd/junction/resave", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionResavePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 修改节点要素信息 Update junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Object</returns>
        public Result<Object> ApiV1ModelInformationDomainWdJunctionUpdatePost (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = ApiV1ModelInformationDomainWdJunctionUpdatePostWithHttpInfo(updateJunctionInput);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 修改节点要素信息 Update junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result< Object >> ApiV1ModelInformationDomainWdJunctionUpdatePostWithHttpInfo (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput))
        {
            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DHICN.PAAS.SDK.ModelInformation.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = updateJunctionInput;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Result< Object >>("/api/v1/model-information/domain-wd/junction/update", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionUpdatePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 修改节点要素信息 Update junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Result<Object>> ApiV1ModelInformationDomainWdJunctionUpdatePostAsync (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput))
        {
             DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>> localVarResponse = await ApiV1ModelInformationDomainWdJunctionUpdatePostAsyncWithHttpInfo(updateJunctionInput);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 修改节点要素信息 Update junction information 
        /// </summary>
        /// <exception cref="DHICN.PAAS.SDK.ModelInformation.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateJunctionInput"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<DHICN.PAAS.SDK.ModelInformation.Client.ApiResponse<Result<Object>>> ApiV1ModelInformationDomainWdJunctionUpdatePostAsyncWithHttpInfo (UpdateJunctionInput updateJunctionInput = default(UpdateJunctionInput))
        {

            DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions localVarRequestOptions = new DHICN.PAAS.SDK.ModelInformation.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = updateJunctionInput;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Result<Object>>("/api/v1/model-information/domain-wd/junction/update", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1ModelInformationDomainWdJunctionUpdatePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
