/* 
 * document-manager-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.DocumentManager.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.DocumentManager.Model
{
    /// <summary>
    /// AddDocumentModel
    /// </summary>
    [DataContract]
    public partial class AddDocumentModel :  IEquatable<AddDocumentModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddDocumentModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddDocumentModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddDocumentModel" /> class.
        /// </summary>
        /// <param name="groupId">groupId.</param>
        /// <param name="docId">docId (required).</param>
        public AddDocumentModel(Guid? groupId = default(Guid?), Guid docId = default(Guid))
        {
            this.DocId = docId;
            this.GroupId = groupId;
        }
        
        /// <summary>
        /// Gets or Sets GroupId
        /// </summary>
        [DataMember(Name="groupId", EmitDefaultValue=true)]
        public Guid? GroupId { get; set; }

        /// <summary>
        /// Gets or Sets DocId
        /// </summary>
        [DataMember(Name="docId", EmitDefaultValue=false)]
        public Guid DocId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddDocumentModel {\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("  DocId: ").Append(DocId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddDocumentModel);
        }

        /// <summary>
        /// Returns true if AddDocumentModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AddDocumentModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddDocumentModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GroupId == input.GroupId ||
                    (this.GroupId != null &&
                    this.GroupId.Equals(input.GroupId))
                ) && 
                (
                    this.DocId == input.DocId ||
                    (this.DocId != null &&
                    this.DocId.Equals(input.DocId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GroupId != null)
                    hashCode = hashCode * 59 + this.GroupId.GetHashCode();
                if (this.DocId != null)
                    hashCode = hashCode * 59 + this.DocId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
