/* 
 * document-manager-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.DocumentManager.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.DocumentManager.Model
{
    /// <summary>
    /// AddingGroupModel
    /// </summary>
    [DataContract]
    public partial class AddingGroupModel :  IEquatable<AddingGroupModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddingGroupModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddingGroupModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddingGroupModel" /> class.
        /// </summary>
        /// <param name="parentGroupId">parentGroupId.</param>
        /// <param name="newGroupName">newGroupName (required).</param>
        public AddingGroupModel(Guid? parentGroupId = default(Guid?), string newGroupName = default(string))
        {
            // to ensure "newGroupName" is required (not null)
            this.NewGroupName = newGroupName ?? throw new ArgumentNullException("newGroupName is a required property for AddingGroupModel and cannot be null");
            this.ParentGroupId = parentGroupId;
        }
        
        /// <summary>
        /// Gets or Sets ParentGroupId
        /// </summary>
        [DataMember(Name="parentGroupId", EmitDefaultValue=true)]
        public Guid? ParentGroupId { get; set; }

        /// <summary>
        /// Gets or Sets NewGroupName
        /// </summary>
        [DataMember(Name="newGroupName", EmitDefaultValue=false)]
        public string NewGroupName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddingGroupModel {\n");
            sb.Append("  ParentGroupId: ").Append(ParentGroupId).Append("\n");
            sb.Append("  NewGroupName: ").Append(NewGroupName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddingGroupModel);
        }

        /// <summary>
        /// Returns true if AddingGroupModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AddingGroupModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddingGroupModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ParentGroupId == input.ParentGroupId ||
                    (this.ParentGroupId != null &&
                    this.ParentGroupId.Equals(input.ParentGroupId))
                ) && 
                (
                    this.NewGroupName == input.NewGroupName ||
                    (this.NewGroupName != null &&
                    this.NewGroupName.Equals(input.NewGroupName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ParentGroupId != null)
                    hashCode = hashCode * 59 + this.ParentGroupId.GetHashCode();
                if (this.NewGroupName != null)
                    hashCode = hashCode * 59 + this.NewGroupName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
