/* 
 * model-information-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.ModelInformation.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.ModelInformation.Model
{
    /// <summary>
    /// GetAllBoundarysOutput
    /// </summary>
    [DataContract]
    public partial class GetAllBoundarysOutput :  IEquatable<GetAllBoundarysOutput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAllBoundarysOutput" /> class.
        /// </summary>
        /// <param name="boundaryID">边界ID boundary id.</param>
        /// <param name="boundaryName">边界名称 boundary name.</param>
        public GetAllBoundarysOutput(string boundaryID = default(string), string boundaryName = default(string))
        {
            this.BoundaryID = boundaryID;
            this.BoundaryName = boundaryName;
        }
        
        /// <summary>
        /// 边界ID boundary id
        /// </summary>
        /// <value>边界ID boundary id</value>
        [DataMember(Name="boundaryID", EmitDefaultValue=true)]
        public string BoundaryID { get; set; }

        /// <summary>
        /// 边界名称 boundary name
        /// </summary>
        /// <value>边界名称 boundary name</value>
        [DataMember(Name="boundaryName", EmitDefaultValue=true)]
        public string BoundaryName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAllBoundarysOutput {\n");
            sb.Append("  BoundaryID: ").Append(BoundaryID).Append("\n");
            sb.Append("  BoundaryName: ").Append(BoundaryName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAllBoundarysOutput);
        }

        /// <summary>
        /// Returns true if GetAllBoundarysOutput instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAllBoundarysOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAllBoundarysOutput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BoundaryID == input.BoundaryID ||
                    (this.BoundaryID != null &&
                    this.BoundaryID.Equals(input.BoundaryID))
                ) && 
                (
                    this.BoundaryName == input.BoundaryName ||
                    (this.BoundaryName != null &&
                    this.BoundaryName.Equals(input.BoundaryName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BoundaryID != null)
                    hashCode = hashCode * 59 + this.BoundaryID.GetHashCode();
                if (this.BoundaryName != null)
                    hashCode = hashCode * 59 + this.BoundaryName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
