/* 
 * model-information-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.ModelInformation.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.ModelInformation.Model
{
    /// <summary>
    /// UpdateWastWaterConditionInput
    /// </summary>
    [DataContract]
    public partial class UpdateWastWaterConditionInput :  IEquatable<UpdateWastWaterConditionInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateWastWaterConditionInput" /> class.
        /// </summary>
        /// <param name="scenarioID">方案ID scenario id.</param>
        /// <param name="boundaryID">边界ID boundary id.</param>
        /// <param name="wasteWaterData">wasteWaterData.</param>
        public UpdateWastWaterConditionInput(string scenarioID = default(string), string boundaryID = default(string), WasteWaterInfo wasteWaterData = default(WasteWaterInfo))
        {
            this.ScenarioID = scenarioID;
            this.BoundaryID = boundaryID;
            this.WasteWaterData = wasteWaterData;
        }
        
        /// <summary>
        /// 方案ID scenario id
        /// </summary>
        /// <value>方案ID scenario id</value>
        [DataMember(Name="scenarioID", EmitDefaultValue=true)]
        public string ScenarioID { get; set; }

        /// <summary>
        /// 边界ID boundary id
        /// </summary>
        /// <value>边界ID boundary id</value>
        [DataMember(Name="boundaryID", EmitDefaultValue=true)]
        public string BoundaryID { get; set; }

        /// <summary>
        /// Gets or Sets WasteWaterData
        /// </summary>
        [DataMember(Name="wasteWaterData", EmitDefaultValue=false)]
        public WasteWaterInfo WasteWaterData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateWastWaterConditionInput {\n");
            sb.Append("  ScenarioID: ").Append(ScenarioID).Append("\n");
            sb.Append("  BoundaryID: ").Append(BoundaryID).Append("\n");
            sb.Append("  WasteWaterData: ").Append(WasteWaterData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateWastWaterConditionInput);
        }

        /// <summary>
        /// Returns true if UpdateWastWaterConditionInput instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateWastWaterConditionInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateWastWaterConditionInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ScenarioID == input.ScenarioID ||
                    (this.ScenarioID != null &&
                    this.ScenarioID.Equals(input.ScenarioID))
                ) && 
                (
                    this.BoundaryID == input.BoundaryID ||
                    (this.BoundaryID != null &&
                    this.BoundaryID.Equals(input.BoundaryID))
                ) && 
                (
                    this.WasteWaterData == input.WasteWaterData ||
                    (this.WasteWaterData != null &&
                    this.WasteWaterData.Equals(input.WasteWaterData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ScenarioID != null)
                    hashCode = hashCode * 59 + this.ScenarioID.GetHashCode();
                if (this.BoundaryID != null)
                    hashCode = hashCode * 59 + this.BoundaryID.GetHashCode();
                if (this.WasteWaterData != null)
                    hashCode = hashCode * 59 + this.WasteWaterData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
