/* 
 * identity-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.Identity.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.Identity.Model
{
    /// <summary>
    /// AddSuperUserInput
    /// </summary>
    [DataContract]
    public partial class AddSuperUserInput :  IEquatable<AddSuperUserInput>, IValidatableObject
    {
        /// <summary>
        /// 0-Normal(normal user) 1-Frozen(frozen user) 2-Cancelled(cancelled user) 
        /// </summary>
        /// <value>0-Normal(normal user) 1-Frozen(frozen user) 2-Cancelled(cancelled user) </value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_2 for value: 2
            /// </summary>
            NUMBER_2 = 2

        }

        /// <summary>
        /// 0-Normal(normal user) 1-Frozen(frozen user) 2-Cancelled(cancelled user) 
        /// </summary>
        /// <value>0-Normal(normal user) 1-Frozen(frozen user) 2-Cancelled(cancelled user) </value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddSuperUserInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddSuperUserInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddSuperUserInput" /> class.
        /// </summary>
        /// <param name="userName">超级用户名 super user name (required).</param>
        /// <param name="surname">姓氏 surname.</param>
        /// <param name="tenantIds">在哪些租户下允许登录 tenant ids for which the super user can login (required).</param>
        /// <param name="status">0-Normal(normal user) 1-Frozen(frozen user) 2-Cancelled(cancelled user)  (required).</param>
        public AddSuperUserInput(string userName = default(string), string surname = default(string), List<Guid> tenantIds = default(List<Guid>), StatusEnum status = default(StatusEnum))
        {
            // to ensure "userName" is required (not null)
            this.UserName = userName ?? throw new ArgumentNullException("userName is a required property for AddSuperUserInput and cannot be null");
            // to ensure "tenantIds" is required (not null)
            this.TenantIds = tenantIds ?? throw new ArgumentNullException("tenantIds is a required property for AddSuperUserInput and cannot be null");
            this.Status = status;
            this.Surname = surname;
        }
        
        /// <summary>
        /// 超级用户名 super user name
        /// </summary>
        /// <value>超级用户名 super user name</value>
        [DataMember(Name="userName", EmitDefaultValue=false)]
        public string UserName { get; set; }

        /// <summary>
        /// 姓氏 surname
        /// </summary>
        /// <value>姓氏 surname</value>
        [DataMember(Name="surname", EmitDefaultValue=true)]
        public string Surname { get; set; }

        /// <summary>
        /// 在哪些租户下允许登录 tenant ids for which the super user can login
        /// </summary>
        /// <value>在哪些租户下允许登录 tenant ids for which the super user can login</value>
        [DataMember(Name="tenantIds", EmitDefaultValue=false)]
        public List<Guid> TenantIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddSuperUserInput {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("  TenantIds: ").Append(TenantIds).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddSuperUserInput);
        }

        /// <summary>
        /// Returns true if AddSuperUserInput instances are equal
        /// </summary>
        /// <param name="input">Instance of AddSuperUserInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddSuperUserInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserName == input.UserName ||
                    (this.UserName != null &&
                    this.UserName.Equals(input.UserName))
                ) && 
                (
                    this.Surname == input.Surname ||
                    (this.Surname != null &&
                    this.Surname.Equals(input.Surname))
                ) && 
                (
                    this.TenantIds == input.TenantIds ||
                    this.TenantIds != null &&
                    input.TenantIds != null &&
                    this.TenantIds.SequenceEqual(input.TenantIds)
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserName != null)
                    hashCode = hashCode * 59 + this.UserName.GetHashCode();
                if (this.Surname != null)
                    hashCode = hashCode * 59 + this.Surname.GetHashCode();
                if (this.TenantIds != null)
                    hashCode = hashCode * 59 + this.TenantIds.GetHashCode();
                hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
