/* 
 * result-analysis-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.ResultAnalysis.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.ResultAnalysis.Model
{
    /// <summary>
    /// 河网断面达标率调度统计
    /// </summary>
    [DataContract]
    public partial class ModelResultRiverQualifiedStatisticOutput :  IEquatable<ModelResultRiverQualifiedStatisticOutput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelResultRiverQualifiedStatisticOutput" /> class.
        /// </summary>
        /// <param name="assetID">断面id section id.</param>
        /// <param name="assetName">断面名称 section name.</param>
        /// <param name="keySectionLocation">考核断面（河道名，里程） assessment section.</param>
        /// <param name="wqInfos">水质最大值列表 list of water quality maximums.</param>
        public ModelResultRiverQualifiedStatisticOutput(string assetID = default(string), string assetName = default(string), string keySectionLocation = default(string), List<WqStatistic> wqInfos = default(List<WqStatistic>))
        {
            this.AssetID = assetID;
            this.AssetName = assetName;
            this.KeySectionLocation = keySectionLocation;
            this.WqInfos = wqInfos;
        }
        
        /// <summary>
        /// 断面id section id
        /// </summary>
        /// <value>断面id section id</value>
        [DataMember(Name="assetID", EmitDefaultValue=true)]
        public string AssetID { get; set; }

        /// <summary>
        /// 断面名称 section name
        /// </summary>
        /// <value>断面名称 section name</value>
        [DataMember(Name="assetName", EmitDefaultValue=true)]
        public string AssetName { get; set; }

        /// <summary>
        /// 考核断面（河道名，里程） assessment section
        /// </summary>
        /// <value>考核断面（河道名，里程） assessment section</value>
        [DataMember(Name="keySectionLocation", EmitDefaultValue=true)]
        public string KeySectionLocation { get; set; }

        /// <summary>
        /// 水质最大值列表 list of water quality maximums
        /// </summary>
        /// <value>水质最大值列表 list of water quality maximums</value>
        [DataMember(Name="wqInfos", EmitDefaultValue=true)]
        public List<WqStatistic> WqInfos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelResultRiverQualifiedStatisticOutput {\n");
            sb.Append("  AssetID: ").Append(AssetID).Append("\n");
            sb.Append("  AssetName: ").Append(AssetName).Append("\n");
            sb.Append("  KeySectionLocation: ").Append(KeySectionLocation).Append("\n");
            sb.Append("  WqInfos: ").Append(WqInfos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelResultRiverQualifiedStatisticOutput);
        }

        /// <summary>
        /// Returns true if ModelResultRiverQualifiedStatisticOutput instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelResultRiverQualifiedStatisticOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelResultRiverQualifiedStatisticOutput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetID == input.AssetID ||
                    (this.AssetID != null &&
                    this.AssetID.Equals(input.AssetID))
                ) && 
                (
                    this.AssetName == input.AssetName ||
                    (this.AssetName != null &&
                    this.AssetName.Equals(input.AssetName))
                ) && 
                (
                    this.KeySectionLocation == input.KeySectionLocation ||
                    (this.KeySectionLocation != null &&
                    this.KeySectionLocation.Equals(input.KeySectionLocation))
                ) && 
                (
                    this.WqInfos == input.WqInfos ||
                    this.WqInfos != null &&
                    input.WqInfos != null &&
                    this.WqInfos.SequenceEqual(input.WqInfos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetID != null)
                    hashCode = hashCode * 59 + this.AssetID.GetHashCode();
                if (this.AssetName != null)
                    hashCode = hashCode * 59 + this.AssetName.GetHashCode();
                if (this.KeySectionLocation != null)
                    hashCode = hashCode * 59 + this.KeySectionLocation.GetHashCode();
                if (this.WqInfos != null)
                    hashCode = hashCode * 59 + this.WqInfos.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
