/* 
 * result-analysis-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.ResultAnalysis.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.ResultAnalysis.Model
{
    /// <summary>
    /// 管网调蓄设置总量运行预报统计
    /// </summary>
    [DataContract]
    public partial class ModelResultPipeStorageStatisticOutput :  IEquatable<ModelResultPipeStorageStatisticOutput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelResultPipeStorageStatisticOutput" /> class.
        /// </summary>
        /// <param name="assetID">资产id assetID.</param>
        /// <param name="assetName">资产名称 asset name.</param>
        /// <param name="storageTotalVolume">调蓄总量 total regulation.</param>
        /// <param name="storageTS">调蓄管道出水量信息 water yield information of regulation and storage pipeline.</param>
        public ModelResultPipeStorageStatisticOutput(string assetID = default(string), string assetName = default(string), double storageTotalVolume = default(double), List<StorageData> storageTS = default(List<StorageData>))
        {
            this.AssetID = assetID;
            this.AssetName = assetName;
            this.StorageTotalVolume = storageTotalVolume;
            this.StorageTS = storageTS;
        }
        
        /// <summary>
        /// 资产id assetID
        /// </summary>
        /// <value>资产id assetID</value>
        [DataMember(Name="assetID", EmitDefaultValue=true)]
        public string AssetID { get; set; }

        /// <summary>
        /// 资产名称 asset name
        /// </summary>
        /// <value>资产名称 asset name</value>
        [DataMember(Name="assetName", EmitDefaultValue=true)]
        public string AssetName { get; set; }

        /// <summary>
        /// 调蓄总量 total regulation
        /// </summary>
        /// <value>调蓄总量 total regulation</value>
        [DataMember(Name="storageTotalVolume", EmitDefaultValue=false)]
        public double StorageTotalVolume { get; set; }

        /// <summary>
        /// 调蓄管道出水量信息 water yield information of regulation and storage pipeline
        /// </summary>
        /// <value>调蓄管道出水量信息 water yield information of regulation and storage pipeline</value>
        [DataMember(Name="storageTS", EmitDefaultValue=true)]
        public List<StorageData> StorageTS { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelResultPipeStorageStatisticOutput {\n");
            sb.Append("  AssetID: ").Append(AssetID).Append("\n");
            sb.Append("  AssetName: ").Append(AssetName).Append("\n");
            sb.Append("  StorageTotalVolume: ").Append(StorageTotalVolume).Append("\n");
            sb.Append("  StorageTS: ").Append(StorageTS).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelResultPipeStorageStatisticOutput);
        }

        /// <summary>
        /// Returns true if ModelResultPipeStorageStatisticOutput instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelResultPipeStorageStatisticOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelResultPipeStorageStatisticOutput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetID == input.AssetID ||
                    (this.AssetID != null &&
                    this.AssetID.Equals(input.AssetID))
                ) && 
                (
                    this.AssetName == input.AssetName ||
                    (this.AssetName != null &&
                    this.AssetName.Equals(input.AssetName))
                ) && 
                (
                    this.StorageTotalVolume == input.StorageTotalVolume ||
                    this.StorageTotalVolume.Equals(input.StorageTotalVolume)
                ) && 
                (
                    this.StorageTS == input.StorageTS ||
                    this.StorageTS != null &&
                    input.StorageTS != null &&
                    this.StorageTS.SequenceEqual(input.StorageTS)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetID != null)
                    hashCode = hashCode * 59 + this.AssetID.GetHashCode();
                if (this.AssetName != null)
                    hashCode = hashCode * 59 + this.AssetName.GetHashCode();
                hashCode = hashCode * 59 + this.StorageTotalVolume.GetHashCode();
                if (this.StorageTS != null)
                    hashCode = hashCode * 59 + this.StorageTS.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
