/* 
 * result-analysis-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DHICN.PAAS.SDK.ResultAnalysis.Client.OpenAPIDateConverter;

namespace DHICN.PAAS.SDK.ResultAnalysis.Model
{
    /// <summary>
    /// 管网调蓄泵站调蓄量统计
    /// </summary>
    [DataContract]
    public partial class ModelResultPipePumpVolumeStatisticOutput :  IEquatable<ModelResultPipePumpVolumeStatisticOutput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelResultPipePumpVolumeStatisticOutput" /> class.
        /// </summary>
        /// <param name="assetName">资产名称 asset name.</param>
        /// <param name="pumpTS">调蓄泵站信息 information of regulation and storage pump.</param>
        public ModelResultPipePumpVolumeStatisticOutput(string assetName = default(string), List<PumpVolume> pumpTS = default(List<PumpVolume>))
        {
            this.AssetName = assetName;
            this.PumpTS = pumpTS;
        }
        
        /// <summary>
        /// 资产名称 asset name
        /// </summary>
        /// <value>资产名称 asset name</value>
        [DataMember(Name="assetName", EmitDefaultValue=true)]
        public string AssetName { get; set; }

        /// <summary>
        /// 调蓄泵站信息 information of regulation and storage pump
        /// </summary>
        /// <value>调蓄泵站信息 information of regulation and storage pump</value>
        [DataMember(Name="pumpTS", EmitDefaultValue=true)]
        public List<PumpVolume> PumpTS { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelResultPipePumpVolumeStatisticOutput {\n");
            sb.Append("  AssetName: ").Append(AssetName).Append("\n");
            sb.Append("  PumpTS: ").Append(PumpTS).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelResultPipePumpVolumeStatisticOutput);
        }

        /// <summary>
        /// Returns true if ModelResultPipePumpVolumeStatisticOutput instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelResultPipePumpVolumeStatisticOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelResultPipePumpVolumeStatisticOutput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetName == input.AssetName ||
                    (this.AssetName != null &&
                    this.AssetName.Equals(input.AssetName))
                ) && 
                (
                    this.PumpTS == input.PumpTS ||
                    this.PumpTS != null &&
                    input.PumpTS != null &&
                    this.PumpTS.SequenceEqual(input.PumpTS)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetName != null)
                    hashCode = hashCode * 59 + this.AssetName.GetHashCode();
                if (this.PumpTS != null)
                    hashCode = hashCode * 59 + this.PumpTS.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
