name: publish nuget

on: 
  push:
    branches: [main]

jobs:
  build:
    strategy: 
        matrix: 
         project: [src/wwtp_paas_main_bus_service]
    runs-on: ubuntu-latest

    steps:
      - name: pre -checkout 
        run: |
            pwd
            ls -lh
      - name: checkout code
        uses: actions/checkout@v3
      - name: after -checkout 
        run: |
            pwd
            ls -lh
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.x'  # .NET版本
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build w --configuration Release --no-restore
      - name: Pack 
        run: dotnet pack  -c Release -o nupkgs  
      - name: Push packages  
        run: |
          dotnet nuget push "nupkgs/*.nupkg"
        env:
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}  # NUGET_API_KEY要作为一个secret创建
